name = "apptivity-public"
main = "worker/index.js"
compatibility_date = "2026-08-15"
workers_dev = true
preview_urls = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[routes]]
pattern = "goapptivity.com/*"
zone_name = "goapptivity.com"

[[routes]]
pattern = "www.goapptivity.com/*"
zone_name = "goapptivity.com"
